{
    'name': 'Motorcycle Stock',
    'version': '0.0.1',
    'author': 'Andres Racines',
    'sequence': -100,
    'category': 'Kawiil/Registry',
    'license': 'OPL-1',
    'depends': ['stock'],
    'data': [],
    'demo':[],
    # 'data': ['views/procuct_template_view.xml'],
    # 'demo': ['demo/product_demo.xml'],
    'application': True,
    'website': 'https://github.com/RacinesAndres',
}
